package models;

import java.io.Serializable;

/**
 * Model class of Actor_film.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActorFilm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Pelicula. */
	private Pelicula pelicula;

	/** Actor. */
	private Actor actor;

	/** actor_name. */
	private String actorName;

	/** film_name. */
	private String filmName;

	/**
	 * Constructor.
	 */
	public ActorFilm() {
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Actor.
	 * 
	 * @param actor
	 *            Actor
	 */
	public void setActor(Actor actor) {
		this.actor = actor;
	}

	/**
	 * Get the Actor.
	 * 
	 * @return Actor
	 */
	public Actor getActor() {
		return this.actor;
	}

	/**
	 * Set the actor_name.
	 * 
	 * @param actorName
	 *            actor_name
	 */
	public void setActorName(String actorName) {
		this.actorName = actorName;
	}

	/**
	 * Get the actor_name.
	 * 
	 * @return actor_name
	 */
	public String getActorName() {
		return this.actorName;
	}

	/**
	 * Set the film_name.
	 * 
	 * @param filmName
	 *            film_name
	 */
	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}

	/**
	 * Get the film_name.
	 * 
	 * @return film_name
	 */
	public String getFilmName() {
		return this.filmName;
	}


}
