package models;
import java.io.Serializable;

/**
 * Model class of Actor_film.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ActorFilm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Composite-id of Actor_film. */
	private ActorFilmId actorFilmId;

	/** Pelicula. */
	private Pelicula pelicula;

	/** Actor. */
	private Actor actor;

	/** actor_name. */
	private String actorName;

	/** film_name. */
	private String filmName;

	/**
	 * Constructor.
	 */
	public ActorFilm() {
	}

	/**
	 * Set the Composite-id of Actor_film.
	 * 
	 * @param actorFilmId
	 *            Composite-id of Actor_film
	 */
	public void setActorFilmId(ActorFilmId actorFilmId) {
		this.actorFilmId = actorFilmId;
	}

	/**
	 * Get the Composite-id of Actor_film.
	 * 
	 * @return Composite-id of Actor_film
	 */
	public ActorFilmId getActorFilmId() {
		return this.actorFilmId;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Actor.
	 * 
	 * @param actor
	 *            Actor
	 */
	public void setActor(Actor actor) {
		this.actor = actor;
	}

	/**
	 * Get the Actor.
	 * 
	 * @return Actor
	 */
	public Actor getActor() {
		return this.actor;
	}

	/**
	 * Set the actor_name.
	 * 
	 * @param actorName
	 *            actor_name
	 */
	public void setActorName(String actorName) {
		this.actorName = actorName;
	}

	/**
	 * Get the actor_name.
	 * 
	 * @return actor_name
	 */
	public String getActorName() {
		return this.actorName;
	}

	/**
	 * Set the film_name.
	 * 
	 * @param filmName
	 *            film_name
	 */
	public void setFilmName(String filmName) {
		this.filmName = filmName;
	}

	/**
	 * Get the film_name.
	 * 
	 * @return film_name
	 */
	public String getFilmName() {
		return this.filmName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actorFilmId == null) ? 0 : actorFilmId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ActorFilm other = (ActorFilm) obj;
		if (actorFilmId == null) {
			if (other.actorFilmId != null) {
				return false;
			}
		} else if (!actorFilmId.equals(other.actorFilmId)) {
			return false;
		}
		return true;
	}

}
