package models;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Company.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Company implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** idcompany. */
	private String idcompany;

	/** name. */
	private String name;

	/** creation_date. */
	private Date creationDate;

	/** The set of company_pelicula. */
	private Set<CompanyPelicula> companyPeliculaSet;

	/**
	 * Constructor.
	 */
	public Company() {
		this.companyPeliculaSet = new HashSet<CompanyPelicula>();
	}

	/**
	 * Set the idcompany.
	 * 
	 * @param idcompany
	 *            idcompany
	 */
	public void setIdcompany(String idcompany) {
		this.idcompany = idcompany;
	}

	/**
	 * Get the idcompany.
	 * 
	 * @return idcompany
	 */
	public String getIdcompany() {
		return this.idcompany;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the creation_date.
	 * 
	 * @param creationDate
	 *            creation_date
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * Get the creation_date.
	 * 
	 * @return creation_date
	 */
	public Date getCreationDate() {
		return this.creationDate;
	}

	/**
	 * Set the set of the company_pelicula.
	 * 
	 * @param companyPeliculaSet
	 *            The set of company_pelicula
	 */
	public void setCompanyPeliculaSet(Set<CompanyPelicula> companyPeliculaSet) {
		this.companyPeliculaSet = companyPeliculaSet;
	}

	/**
	 * Add the company_pelicula.
	 * 
	 * @param companyPelicula
	 *            company_pelicula
	 */
	public void addCompanyPelicula(CompanyPelicula companyPelicula) {
		this.companyPeliculaSet.add(companyPelicula);
	}

	/**
	 * Get the set of the company_pelicula.
	 * 
	 * @return The set of company_pelicula
	 */
	public Set<CompanyPelicula> getCompanyPeliculaSet() {
		return this.companyPeliculaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idcompany == null) ? 0 : idcompany.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Company other = (Company) obj;
		if (idcompany == null) {
			if (other.idcompany != null) {
				return false;
			}
		} else if (!idcompany.equals(other.idcompany)) {
			return false;
		}
		return true;
	}

}
