package models;
import java.io.Serializable;

/**
 * Composite-id class of company_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyPeliculaId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Company. */
	private Company company;

	/** Pelicula. */
	private Pelicula pelicula;

	/**
	 * Constructor.
	 */
	public CompanyPeliculaId() {
	}

	/**
	 * Set the Company.
	 * 
	 * @param company
	 *            Company
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the Company.
	 * 
	 * @return Company
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((company == null) ? 0 : company.hashCode());
		result = prime * result + ((pelicula == null) ? 0 : pelicula.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyPeliculaId other = (CompanyPeliculaId) obj;
		if (company == null) {
			if (other.company != null) {
				return false;
			}
		} else if (!company.equals(other.company)) {
			return false;
		}
		if (pelicula == null) {
			if (other.pelicula != null) {
				return false;
			}
		} else if (!pelicula.equals(other.pelicula)) {
			return false;
		}
		return true;
	}

}
