package models;
import java.io.Serializable;

/**
 * Model class of company_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyPelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Composite-id of company_pelicula. */
	private CompanyPeliculaId companyPeliculaId;

	/** Company. */
	private Company company;

	/** Pelicula. */
	private Pelicula pelicula;

	/**
	 * Constructor.
	 */
	public CompanyPelicula() {
	}

	/**
	 * Set the Composite-id of company_pelicula.
	 * 
	 * @param companyPeliculaId
	 *            Composite-id of company_pelicula
	 */
	public void setCompanyPeliculaId(CompanyPeliculaId companyPeliculaId) {
		this.companyPeliculaId = companyPeliculaId;
	}

	/**
	 * Get the Composite-id of company_pelicula.
	 * 
	 * @return Composite-id of company_pelicula
	 */
	public CompanyPeliculaId getCompanyPeliculaId() {
		return this.companyPeliculaId;
	}

	/**
	 * Set the Company.
	 * 
	 * @param company
	 *            Company
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the Company.
	 * 
	 * @return Company
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((companyPeliculaId == null) ? 0 : companyPeliculaId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompanyPelicula other = (CompanyPelicula) obj;
		if (companyPeliculaId == null) {
			if (other.companyPeliculaId != null) {
				return false;
			}
		} else if (!companyPeliculaId.equals(other.companyPeliculaId)) {
			return false;
		}
		return true;
	}

}
