package models;
import java.io.Serializable;

/**
 * Model class of company_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyPelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Composite-id of company_pelicula. */
	

	/** Company. */
	public String companyid;

	/** Pelicula. */
	public String peliculaid;

	public String getCompanyid() {
		return companyid;
	}


	public void setCompanyid(String companyid) {
		this.companyid = companyid;
	}


	public String getPeliculaid() {
		return peliculaid;
	}


	public void setPeliculaid(String peliculaid) {
		this.peliculaid = peliculaid;
	}


	/**
	 * Constructor.
	 */
	public CompanyPelicula(String idcompany, String peliculaid) {
		this.companyid = idcompany;
		this.peliculaid = peliculaid;
		
	}


	/**
	 * Set the Company.
	 * 
	 * @param company
	 *            Company
	 */
	public void setCompany(String company) {
		this.companyid = company;
	}

	/**
	 * Get the Company.
	 * 
	 * @return Company
	 */
	public String getCompany() {
		return this.companyid;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(String pelicula) {
		this.peliculaid = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public String getPelicula() {
		return this.peliculaid;
	}



}
