package models;

import java.io.Serializable;

/**
 * Model class of director_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DirectorPelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Pelicula. */
	private Pelicula pelicula;

	/** Director. */
	private Director director;

	/**
	 * Constructor.
	 */
	public DirectorPelicula() {
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Director.
	 * 
	 * @param director
	 *            Director
	 */
	public void setDirector(Director director) {
		this.director = director;
	}

	/**
	 * Get the Director.
	 * 
	 * @return Director
	 */
	public Director getDirector() {
		return this.director;
	}


}
