package models;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Director.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Director implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** iddirector. */
	private String iddirector;

	/** name. */
	private String name;

	/** born. */
	private Date born;

	/** The set of director_pelicula. */
	private Set<DirectorPelicula> directorPeliculaSet;

	/**
	 * Constructor.
	 */
	public Director() {
		this.directorPeliculaSet = new HashSet<DirectorPelicula>();
	}

	/**
	 * Set the iddirector.
	 * 
	 * @param iddirector
	 *            iddirector
	 */
	public void setIddirector(String iddirector) {
		this.iddirector = iddirector;
	}

	/**
	 * Get the iddirector.
	 * 
	 * @return iddirector
	 */
	public String getIddirector() {
		return this.iddirector;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the born.
	 * 
	 * @param born
	 *            born
	 */
	public void setBorn(Date born) {
		this.born = born;
	}

	/**
	 * Get the born.
	 * 
	 * @return born
	 */
	public Date getBorn() {
		return this.born;
	}

	/**
	 * Set the set of the director_pelicula.
	 * 
	 * @param directorPeliculaSet
	 *            The set of director_pelicula
	 */
	public void setDirectorPeliculaSet(Set<DirectorPelicula> directorPeliculaSet) {
		this.directorPeliculaSet = directorPeliculaSet;
	}

	/**
	 * Add the director_pelicula.
	 * 
	 * @param directorPelicula
	 *            director_pelicula
	 */
	public void addDirectorPelicula(DirectorPelicula directorPelicula) {
		this.directorPeliculaSet.add(directorPelicula);
	}

	/**
	 * Get the set of the director_pelicula.
	 * 
	 * @return The set of director_pelicula
	 */
	public Set<DirectorPelicula> getDirectorPeliculaSet() {
		return this.directorPeliculaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((iddirector == null) ? 0 : iddirector.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Director other = (Director) obj;
		if (iddirector == null) {
			if (other.iddirector != null) {
				return false;
			}
		} else if (!iddirector.equals(other.iddirector)) {
			return false;
		}
		return true;
	}

}
