package models;
import java.io.Serializable;

/**
 * Composite-id class of genre_film.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GenreFilmId implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Pelicula. */
	private Pelicula pelicula;

	/** Genres. */
	private Genres genres;

	/**
	 * Constructor.
	 */
	public GenreFilmId() {
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Genres.
	 * 
	 * @param genres
	 *            Genres
	 */
	public void setGenres(Genres genres) {
		this.genres = genres;
	}

	/**
	 * Get the Genres.
	 * 
	 * @return Genres
	 */
	public Genres getGenres() {
		return this.genres;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pelicula == null) ? 0 : pelicula.hashCode());
		result = prime * result + ((genres == null) ? 0 : genres.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GenreFilmId other = (GenreFilmId) obj;
		if (pelicula == null) {
			if (other.pelicula != null) {
				return false;
			}
		} else if (!pelicula.equals(other.pelicula)) {
			return false;
		}
		if (genres == null) {
			if (other.genres != null) {
				return false;
			}
		} else if (!genres.equals(other.genres)) {
			return false;
		}
		return true;
	}

}
