package models;
import java.io.Serializable;

/**
 * Model class of genre_film.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GenreFilm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Composite-id of genre_film. */
	private GenreFilmId genreFilmId;

	/** Pelicula. */
	public String pelicula;

	/** Genres. */
	public String genres;

	/** genre_name. */
	private String genreName;

	/**
	 * Constructor.
	 */
	public GenreFilm(String genre, String pelicula) {
		this.genres = genre;
		this.pelicula = pelicula;
	}

	@Override
	public String toString() {
		return "GenreFilm [pelicula=" + pelicula + ", genres=" + genres + "]";
	}

	/**
	 * Set the Composite-id of genre_film.
	 * 
	 * @param genreFilmId
	 *            Composite-id of genre_film
	 */
	public void setGenreFilmId(GenreFilmId genreFilmId) {
		this.genreFilmId = genreFilmId;
	}

	/**
	 * Get the Composite-id of genre_film.
	 * 
	 * @return Composite-id of genre_film
	 */
	public GenreFilmId getGenreFilmId() {
		return this.genreFilmId;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(String pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public String getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Genres.
	 * 
	 * @param genres
	 *            Genres
	 */
	public void setGenres(String genres) {
		this.genres = genres;
	}

	/**
	 * Get the Genres.
	 * 
	 * @return Genres
	 */
	public String getGenres() {
		return this.genres;
	}

	/**
	 * Set the genre_name.
	 * 
	 * @param genreName
	 *            genre_name
	 */
	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}

	/**
	 * Get the genre_name.
	 * 
	 * @return genre_name
	 */
	public String getGenreName() {
		return this.genreName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((genreFilmId == null) ? 0 : genreFilmId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		GenreFilm other = (GenreFilm) obj;
		if (genreFilmId == null) {
			if (other.genreFilmId != null) {
				return false;
			}
		} else if (!genreFilmId.equals(other.genreFilmId)) {
			return false;
		}
		return true;
	}

}
