package models;

import java.io.Serializable;

/**
 * Model class of genre_film.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GenreFilm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Pelicula. */
	private Pelicula pelicula;

	/** Genres. */
	private Genres genres;

	/** genre_name. */
	private String genreName;

	/**
	 * Constructor.
	 */
	public GenreFilm() {
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * Set the Genres.
	 * 
	 * @param genres
	 *            Genres
	 */
	public void setGenres(Genres genres) {
		this.genres = genres;
	}

	/**
	 * Get the Genres.
	 * 
	 * @return Genres
	 */
	public Genres getGenres() {
		return this.genres;
	}

	/**
	 * Set the genre_name.
	 * 
	 * @param genreName
	 *            genre_name
	 */
	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}

	/**
	 * Get the genre_name.
	 * 
	 * @return genre_name
	 */
	public String getGenreName() {
		return this.genreName;
	}


}
