package models;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Pelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	public String id;

	/** title. */
	public String title;

	/** year. */
	public Integer year;

	/** duration. */
	public Integer duration;

	/** description. */
	public String description;

	/** poster. */
	public String poster;

	/** valoration. */
	public Double valoration;

	/** director. */
	public String director;

	/** full_title. */
	public String fullTitle;

	/** image. */
	public String image;

	/** type. */
	public String type;

	/** release_date. */
	public String releaseDate;

	/** The set of Actor_film. */
	private Set<ActorFilm> actorFilmSet;

	/** The set of company_pelicula. */
	private Set<CompanyPelicula> companyPeliculaSet;

	/** The set of director_pelicula. */
	private Set<DirectorPelicula> directorPeliculaSet;

	/** The set of genre_film. */
	private Set<GenreFilm> genreFilmSet;

	/** The set of usuario_pelicula. */
	private Set<UsuarioPelicula> usuarioPeliculaSet;

	/**
	 * Constructor.
	 * @param releaseDate
	 * @param type
	 * @param image
	 * @param fullTitle
	 * @param director
	 * @param valoration
	 * @param poster
	 * @param description
	 * @param duration
	 * @param year
	 * @param title
	 * @param id
	 */
	public Pelicula(String id, String title, Integer year, Integer duration, String description, String poster, Double valoration, String director, String fullTitle, String image, String type, String releaseDate) {
		this.id =id;
		this.title=title;
		this.year = year;
		this.duration=duration;
		this.description=description;
		this.poster=poster;
		this.valoration=valoration;
		this.fullTitle =fullTitle;
		this.image = image;
		this.type=type;
		this.releaseDate=releaseDate;
		this.director =director;
		this.actorFilmSet = new HashSet<ActorFilm>();
		this.companyPeliculaSet = new HashSet<CompanyPelicula>();
		this.directorPeliculaSet = new HashSet<DirectorPelicula>();
		this.genreFilmSet = new HashSet<GenreFilm>();
		this.usuarioPeliculaSet = new HashSet<UsuarioPelicula>();
	}
	


	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Pelicula [id=" + id + ", title=" + title + ", year=" + year + ", duration=" + duration
				+ ", description=" + description + ", poster=" + poster + ", valoration=" + valoration + ", director="
				+ director + ", fullTitle=" + fullTitle + ", image=" + image + ", type=" + type + ", releaseDate="
				+ releaseDate + ", actorFilmSet=" + actorFilmSet + ", companyPeliculaSet=" + companyPeliculaSet
				+ ", directorPeliculaSet=" + directorPeliculaSet + ", genreFilmSet=" + genreFilmSet
				+ ", usuarioPeliculaSet=" + usuarioPeliculaSet + "]";
	}



	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the year.
	 * 
	 * @param year
	 *            year
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * Get the year.
	 * 
	 * @return year
	 */
	public Integer getYear() {
		return this.year;
	}

	/**
	 * Set the duration.
	 * 
	 * @param duration
	 *            duration
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * Get the duration.
	 * 
	 * @return duration
	 */
	public Integer getDuration() {
		return this.duration;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the poster.
	 * 
	 * @param poster
	 *            poster
	 */
	public void setPoster(String poster) {
		this.poster = poster;
	}

	/**
	 * Get the poster.
	 * 
	 * @return poster
	 */
	public String getPoster() {
		return this.poster;
	}

	/**
	 * Set the valoration.
	 * 
	 * @param valoration
	 *            valoration
	 */
	public void setValoration(Double valoration) {
		this.valoration = valoration;
	}

	/**
	 * Get the valoration.
	 * 
	 * @return valoration
	 */
	public Double getValoration() {
		return this.valoration;
	}

	/**
	 * Set the director.
	 * 
	 * @param director
	 *            director
	 */
	public void setDirector(String director) {
		this.director = director;
	}

	/**
	 * Get the director.
	 * 
	 * @return director
	 */
	public String getDirector() {
		return this.director;
	}

	/**
	 * Set the full_title.
	 * 
	 * @param fullTitle
	 *            full_title
	 */
	public void setFullTitle(String fullTitle) {
		this.fullTitle = fullTitle;
	}

	/**
	 * Get the full_title.
	 * 
	 * @return full_title
	 */
	public String getFullTitle() {
		return this.fullTitle;
	}

	/**
	 * Set the image.
	 * 
	 * @param image
	 *            image
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * Get the image.
	 * 
	 * @return image
	 */
	public String getImage() {
		return this.image;
	}

	/**
	 * Set the type.
	 * 
	 * @param type
	 *            type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Get the type.
	 * 
	 * @return type
	 */
	public String getType() {
		return this.type;
	}

	/**
	 * Set the release_date.
	 * 
	 * @param releaseDate
	 *            release_date
	 */
	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}

	/**
	 * Get the release_date.
	 * 
	 * @return release_date
	 */
	public String getReleaseDate() {
		return this.releaseDate;
	}

	/**
	 * Set the set of the Actor_film.
	 * 
	 * @param actorFilmSet
	 *            The set of Actor_film
	 */
	public void setActorFilmSet(Set<ActorFilm> actorFilmSet) {
		this.actorFilmSet = actorFilmSet;
	}

	/**
	 * Add the Actor_film.
	 * 
	 * @param actorFilm
	 *            Actor_film
	 */
	public void addActorFilm(ActorFilm actorFilm) {
		this.actorFilmSet.add(actorFilm);
	}

	/**
	 * Get the set of the Actor_film.
	 * 
	 * @return The set of Actor_film
	 */
	public Set<ActorFilm> getActorFilmSet() {
		return this.actorFilmSet;
	}

	/**
	 * Set the set of the company_pelicula.
	 * 
	 * @param companyPeliculaSet
	 *            The set of company_pelicula
	 */
	public void setCompanyPeliculaSet(Set<CompanyPelicula> companyPeliculaSet) {
		this.companyPeliculaSet = companyPeliculaSet;
	}

	/**
	 * Add the company_pelicula.
	 * 
	 * @param companyPelicula
	 *            company_pelicula
	 */
	public void addCompanyPelicula(CompanyPelicula companyPelicula) {
		this.companyPeliculaSet.add(companyPelicula);
	}

	/**
	 * Get the set of the company_pelicula.
	 * 
	 * @return The set of company_pelicula
	 */
	public Set<CompanyPelicula> getCompanyPeliculaSet() {
		return this.companyPeliculaSet;
	}

	/**
	 * Set the set of the director_pelicula.
	 * 
	 * @param directorPeliculaSet
	 *            The set of director_pelicula
	 */
	public void setDirectorPeliculaSet(Set<DirectorPelicula> directorPeliculaSet) {
		this.directorPeliculaSet = directorPeliculaSet;
	}

	/**
	 * Add the director_pelicula.
	 * 
	 * @param directorPelicula
	 *            director_pelicula
	 */
	public void addDirectorPelicula(DirectorPelicula directorPelicula) {
		this.directorPeliculaSet.add(directorPelicula);
	}

	/**
	 * Get the set of the director_pelicula.
	 * 
	 * @return The set of director_pelicula
	 */
	public Set<DirectorPelicula> getDirectorPeliculaSet() {
		return this.directorPeliculaSet;
	}

	/**
	 * Set the set of the genre_film.
	 * 
	 * @param genreFilmSet
	 *            The set of genre_film
	 */
	public void setGenreFilmSet(Set<GenreFilm> genreFilmSet) {
		this.genreFilmSet = genreFilmSet;
	}

	/**
	 * Add the genre_film.
	 * 
	 * @param genreFilm
	 *            genre_film
	 */
	public void addGenreFilm(GenreFilm genreFilm) {
		this.genreFilmSet.add(genreFilm);
	}

	/**
	 * Get the set of the genre_film.
	 * 
	 * @return The set of genre_film
	 */
	public Set<GenreFilm> getGenreFilmSet() {
		return this.genreFilmSet;
	}

	/**
	 * Set the set of the usuario_pelicula.
	 * 
	 * @param usuarioPeliculaSet
	 *            The set of usuario_pelicula
	 */
	public void setUsuarioPeliculaSet(Set<UsuarioPelicula> usuarioPeliculaSet) {
		this.usuarioPeliculaSet = usuarioPeliculaSet;
	}

	/**
	 * Add the usuario_pelicula.
	 * 
	 * @param usuarioPelicula
	 *            usuario_pelicula
	 */
	public void addUsuarioPelicula(UsuarioPelicula usuarioPelicula) {
		this.usuarioPeliculaSet.add(usuarioPelicula);
	}

	/**
	 * Get the set of the usuario_pelicula.
	 * 
	 * @return The set of usuario_pelicula
	 */
	public Set<UsuarioPelicula> getUsuarioPeliculaSet() {
		return this.usuarioPeliculaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Pelicula other = (Pelicula) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
