package models;
import java.io.Serializable;

/**
 * Model class of usuario_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UsuarioPelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Composite-id of usuario_pelicula. */
	private UsuarioPeliculaId usuarioPeliculaId;

	/** usuario. */
	private Usuario usuario;

	/** Pelicula. */
	private Pelicula pelicula;

	/**
	 * Constructor.
	 */
	public UsuarioPelicula() {
	}

	/**
	 * Set the Composite-id of usuario_pelicula.
	 * 
	 * @param usuarioPeliculaId
	 *            Composite-id of usuario_pelicula
	 */
	public void setUsuarioPeliculaId(UsuarioPeliculaId usuarioPeliculaId) {
		this.usuarioPeliculaId = usuarioPeliculaId;
	}

	/**
	 * Get the Composite-id of usuario_pelicula.
	 * 
	 * @return Composite-id of usuario_pelicula
	 */
	public UsuarioPeliculaId getUsuarioPeliculaId() {
		return this.usuarioPeliculaId;
	}

	/**
	 * Set the usuario.
	 * 
	 * @param usuario
	 *            usuario
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * Get the usuario.
	 * 
	 * @return usuario
	 */
	public Usuario getUsuario() {
		return this.usuario;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((usuarioPeliculaId == null) ? 0 : usuarioPeliculaId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UsuarioPelicula other = (UsuarioPelicula) obj;
		if (usuarioPeliculaId == null) {
			if (other.usuarioPeliculaId != null) {
				return false;
			}
		} else if (!usuarioPeliculaId.equals(other.usuarioPeliculaId)) {
			return false;
		}
		return true;
	}

}
