package models;

import java.io.Serializable;

/**
 * Model class of usuario_pelicula.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UsuarioPelicula implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** usuario. */
	private Usuario usuario;

	/** Pelicula. */
	private Pelicula pelicula;

	/**
	 * Constructor.
	 */
	public UsuarioPelicula() {
	}

	/**
	 * Set the usuario.
	 * 
	 * @param usuario
	 *            usuario
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * Get the usuario.
	 * 
	 * @return usuario
	 */
	public Usuario getUsuario() {
		return this.usuario;
	}

	/**
	 * Set the Pelicula.
	 * 
	 * @param pelicula
	 *            Pelicula
	 */
	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	/**
	 * Get the Pelicula.
	 * 
	 * @return Pelicula
	 */
	public Pelicula getPelicula() {
		return this.pelicula;
	}


}
