package models;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of usuario.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Usuario implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** idusuario. */
	private Integer idusuario;

	/** name. */
	private String name;

	/** password. */
	private String password;

	/** email. */
	private String email;

	/** The set of usuario_pelicula. */
	private Set<UsuarioPelicula> usuarioPeliculaSet;

	/**
	 * Constructor.
	 */
	public Usuario() {
		this.usuarioPeliculaSet = new HashSet<UsuarioPelicula>();
	}

	/**
	 * Set the idusuario.
	 * 
	 * @param idusuario
	 *            idusuario
	 */
	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	/**
	 * Get the idusuario.
	 * 
	 * @return idusuario
	 */
	public Integer getIdusuario() {
		return this.idusuario;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the set of the usuario_pelicula.
	 * 
	 * @param usuarioPeliculaSet
	 *            The set of usuario_pelicula
	 */
	public void setUsuarioPeliculaSet(Set<UsuarioPelicula> usuarioPeliculaSet) {
		this.usuarioPeliculaSet = usuarioPeliculaSet;
	}

	/**
	 * Add the usuario_pelicula.
	 * 
	 * @param usuarioPelicula
	 *            usuario_pelicula
	 */
	public void addUsuarioPelicula(UsuarioPelicula usuarioPelicula) {
		this.usuarioPeliculaSet.add(usuarioPelicula);
	}

	/**
	 * Get the set of the usuario_pelicula.
	 * 
	 * @return The set of usuario_pelicula
	 */
	public Set<UsuarioPelicula> getUsuarioPeliculaSet() {
		return this.usuarioPeliculaSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idusuario == null) ? 0 : idusuario.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Usuario other = (Usuario) obj;
		if (idusuario == null) {
			if (other.idusuario != null) {
				return false;
			}
		} else if (!idusuario.equals(other.idusuario)) {
			return false;
		}
		return true;
	}

}
